SUPABASE_URL = "https://sttnlyunyemkahfoiiti.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0dG5seXVueWVta2FoZm9paXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzE4NzcsImV4cCI6MjA3MjA0Nzg3N30.ICSQdkRSYUQZD__vQiXe3O2TbIUQ_CvUeO7v7ORuR6k"
